Адаптивная сетка
htmlacademy-adaptive/1952495-cat-energy-27 pull request #4
Opened 2022-12-28 22:10 UTC by IvanDolgikh

2022-12-31 07:22 UTC, craz3r requested changes
На страницах каталога и формы в режиме десктопа в хедере отображается кот на зеленом фоне, хотя по макету он должен быть только на главной

2022-12-31 07:22 UTC, craz3r commented on source/catalog.html
> +              <a class="main-nav__item-link item-link--change-color" href="#">Главная</a>
Нужно добавить атрибуты href

2022-12-31 07:22 UTC, craz3r commented on source/less/blocks/catalog/additional-products.less
> +  @media (min-width: @tablet) and (max-width: @desktop) {
Вторая часть условия необязательна, все равно ниже идут правила только для десктопа.

2022-12-31 11:25 UTC, IvanDolgikh commented on source/catalog.html
> +              <a class="main-nav__item-link item-link--change-color" href="#">Главная</a>
А они там есть только после класса

2023-01-05 07:43 UTC, craz3r commented on source/catalog.html
> +              <a class="main-nav__item-link item-link--change-color" href="#">Главная</a>
Так ведь он пустой, на странице каталога в на этом месте должна быть ссылка на главную страницу

2023-01-05 07:45 UTC, merged